name: k6 Performance Test - Cloud
on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Authenticate k6
        run: k6 cloud login --token $K6_CLOUD_TOKEN
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      - name: Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load_k6_test.js
          cloud: true
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
